FROM ghcr.io/astral-sh/uv:python3.14-trixie-slim@sha256:00facf17b58b02b725155862c5cd637f688f906bf7eb5b5194647886d8805cf3

WORKDIR /app
ENV UV_COMPILE_BYTECODE=1

COPY pyproject.toml uv.lock .python-version ./
RUN uv sync --locked

COPY src ./src
COPY migrations ./migrations
COPY scripts ./scripts
COPY tests ./tests

CMD ["uv", "run", "-m", "src.main"]
