{{- if and .Values.database.url (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redoost.databaseSecretName" . }}
  labels:
    {{- include "redoost.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
stringData:
  REDOOST_DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
