apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redoost.fullname" . }}-api-data
  labels:
    {{- include "redoost.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.api.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.api.persistence.size }}
