apiVersion: v1
kind: Service
metadata:
  name: {{ include "redoost.fullname" . }}-api
  labels:
    {{- include "redoost.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "redoost.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
