apiVersion: v1
kind: Service
metadata:
  name: {{ include "redoost.fullname" . }}-sites
  labels:
    {{- include "redoost.labels" . | nindent 4 }}
    app.kubernetes.io/component: sites
spec:
  selector:
    {{- include "redoost.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sites
  ports:
    - name: http
      port: 8080
      targetPort: http
