"""Add site lifetime

Revision ID: 3b53fb008630
Revises: 04b8482583ba
Create Date: 2026-09-26 15:18:27.526248

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

revision: str = "3b53fb008630"
down_revision: str | Sequence[str] | None = "04b8482583ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "available_until", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.drop_column("available_until")

    # ### end Alembic commands ###
