"""Add users

Revision ID: 99592f2fca1b
Revises: 5e0ea8a27714
Create Date: 2026-10-02 00:50:30.315310

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

revision: str = "99592f2fca1b"
down_revision: str | Sequence[str] | None = "5e0ea8a27714"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Deployments now need an owner, so existing ones have to be removed first
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sa.Enum("google", name="provider"), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "subject"),
    )
    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("owner_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )
        batch_op.drop_index(batch_op.f("ix_deployment_token_hash"))
        batch_op.create_index(
            batch_op.f("ix_deployment_owner_id"), ["owner_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_deployment_owner_id_users", "users", ["owner_id"], ["id"]
        )
        batch_op.drop_column("token_hash")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.add_column(sa.Column("token_hash", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint("fk_deployment_owner_id_users", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_deployment_owner_id"))
        batch_op.create_index(
            batch_op.f("ix_deployment_token_hash"), ["token_hash"], unique=False
        )
        batch_op.drop_column("owner_id")

    op.drop_table("users")
    # ### end Alembic commands ###
    # Postgres keeps enum types after their table is dropped
    sa.Enum(name="provider").drop(op.get_bind(), checkfirst=True)
