"""Remove anonymous users

Revision ID: f073df941a6c
Revises: 99592f2fca1b
Create Date: 2026-10-09 03:02:23.323860

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

revision: str = "f073df941a6c"
down_revision: str | Sequence[str] | None = "99592f2fca1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Anonymous users go with their sites; cleanup then removes the files
    op.execute(
        "DELETE FROM deployment WHERE owner_id IN"
        " (SELECT id FROM users WHERE provider IS NULL)"
    )
    op.execute("DELETE FROM users WHERE provider IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.drop_column("available_until")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "provider",
            existing_type=sa.Enum("google", name="provider"),
            nullable=False,
        )
        batch_op.alter_column("subject", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("subject", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.alter_column(
            "provider",
            existing_type=sa.Enum("google", name="provider"),
            nullable=True,
        )

    with op.batch_alter_table("deployment", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "available_until",
                sqlmodel.sql.sqltypes.UTCDateTime(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###
